### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by fsill99** [DarioSpinosa/Legacy-Of-Goku-Release#1]
Hi, 

where is the source code? 

I found **only** binaries, please fix.

**Comment by raezon** [comment]
xD it's the game what do you want by source code

**Comment by Kaitenjo** [comment]
> xD it's the game what do you want by source code

It's a friend of mine who likes to troll me

**Comment by fsill99** [comment]
This issue is still open after 1 year, please fix it
