### ISSUE TITLE
Bug: Using A button on controller to activate save point/talk to NPC also performs skill

### ISSUE THREAD

**Issue by Monkeor** [DarioSpinosa/Legacy-Of-Goku-Release#2]
Using the A button to activate a save point or to talk to an NPC also activates the skill associated with the A button, draining your energy.

**Comment by Kaitenjo** [comment]
There's no skill associated to the A button
To save or talk to npc you need to press Q
All the abilities that drain energy are on Space, H, K, and L keys

> Using the A button to activate a save point or to talk to an NPC also activates the skill associated with the A button, draining your energy.
