### ISSUE TITLE
Bug?: Using dash attack on T-Rex damages you

### ISSUE THREAD

**Issue by Monkeor** [DarioSpinosa/Legacy-Of-Goku-Release#3]
I'm assuming the T-Rex is just attacking on the same frame the dash attack hits it, cancelling both of your attacks, but it happens consistently and only has the effect of making the dash attack useless against it. I'm guessing the range of the T-Rex's attack and the player's dashing hitbox should be changed.

**Comment by Kaitenjo** [comment]
The t rex's hitbox was not disabled correctly. 
This bug has been fixed

> I'm assuming the T-Rex is just attacking on the same frame the dash attack hits it, cancelling both of your attacks, but it happens consistently and only has the effect of making the dash attack useless against it. I'm guessing the range of the T-Rex's attack and the player's dashing hitbox should be changed.
