### ISSUE TITLE
Bug: Final Flash audio keeps playing

### ISSUE THREAD

**Issue by Monkeor** [DarioSpinosa/Legacy-Of-Goku-Release#4]
The beam audio sometimes loops infinitely after FF is used. It keeps playing after dying as well.

**Comment by DarioSpinosa** [comment]
Fixed in 1.1.3

**Comment by Kaitenjo** [comment]
Fixed in 1.1.3

> The beam audio sometimes loops infinitely after FF is used. It keeps playing after dying as well.
