### ISSUE TITLE
Bug?: Player melee hitbox issues

### ISSUE THREAD

**Issue by Monkeor** [DarioSpinosa/Legacy-Of-Goku-Release#7]
I wish I could say with more certainty what's going on, but many situations where it feels like the player's attacks should definitely hit the enemy, they don't. It feels like the hitbox for player melee attacks is significantly more narrow and a bit shorter than it was in LoG2 and Buu's Fury.

https://streamable.com/xkom67

**Comment by Kaitenjo** [comment]
The vertical and horizontal hitboxes were activating in reverse. The issue has been resolved, and I have increased the dimensions of the hitboxes for wolves and tiger-men as they were still too small even after the fix.

> I wish I could say with more certainty what's going on, but many situations where it feels like the player's attacks should definitely hit the enemy, they don't. It feels like the hitbox for player melee attacks is significantly more narrow and a bit shorter than it was in LoG2 and Buu's Fury.
> 
> https://streamable.com/xkom67
